version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "8080:3000" #host:container
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todo
    networks:
      - app-network
    depends_on:
      - postgres

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge